# Generated by Django 3.2.4 on 2021-06-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_event_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
    ]
